/**
 * F채ngt eine Exception einer async Funktion ab und gibt die Fehlermeldung oder die R체ckgabe zur체ck
 * @param promise Promise R체ckgabe von einer asnyc Funktion
 * @returns [data,error]
 */
export default function resolve(promise:Promise<any>)
{
    return promise.then(data => {return [data,null]})
    .catch(err =>
        {
            console.error(err);
            return [null,err]
        });
}